spring.application.name=mrisk



server.port=9003



####    SRPING CLOUD CONFIG    ####
#spring.config.import=optional:configserver:http://localhost:9101
# Must be reactivated after
spring.cloud.config.enabled=false



####    EUREKA    ####
#eureka.client.enabled=false
eureka.client.serviceUrl.defaultZone:http://localhost:9102/eureka/
# Forcer IP locale au lieu du hostname de entreprise
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
# Pour recuperer le registre des services
eureka.client.fetch-registry=true



####  DISTRIBUTED TRACING  - SPRING CLOUD SLEUTH - MICROMETER TRACING  ####
#management.tracing.enabled=false
# Configuration pour chaque microservice (mgateway, clientui, mpatient, mnotes, mrisk)

# Configuration des endpoints Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus,tracing

# Configuration du tracing distribue
# 100% des traces (reduire en production ex: 0.1 pour 10%)
management.tracing.sampling.probability=1.0

# Configuration Zipkin
#management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans        obsolete pour Micrometer Tracing
# recommandee pour Micrometer Tracing
management.tracing.zipkin.endpoint=http://localhost:9411/api/v2/spans
# Ou si Zipkin est dans un container Docker :
# management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# Configuration des logs pour inclure les trace ID et span ID
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]



####    APPLICATION INFORMATION    ####
info.app.version=mrisk - Version en cours de developpement
info.app.description=mrisk- MicroDiab, application d'analyse du diabete des patients
info.app.documentation=mrisk- Lien vers la documentation de l'application
info.app.information=mrisk- Informations utiles


# Ajoute un log pour confirmer que le serveur Tomcat demarre :
#logging.level.org.springframework.boot.web.servlet.context=DEBUG
#logging.level.org.apache.catalina=DEBUG

